exports.OrderService = {
  PENDING: "PENDING",
  ORDERED: "ORDERED",
  ACCEPTED: "ACCEPTED",
  ONTHEWAY: "ONTHEWAY",
  WORKING: "WORKING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

exports.OrderEcommerce = {
  PENDING: "PENDING",
  ORDERED: "ORDERED",
  CANCELLED: "CANCELLED",
  ACCEPTED: "ACCEPTED",
  OUT_OF_DELIVERY: "OUT_OF_DELIVERY",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  RETURN_REQUEST: "RETURN_REQUEST",
  RETURN_REQUEST_APPROVED: "RETURN_REQUEST_APPROVED",
  RETURNED: "RETURNED",
  MULTI_STATUS: "MULTI_STATUS",
  
};
